In [11]:
import pandas as pd
x=['Python', 'Pandas'] 
df = pd.DataFrame(x)
print (pd)

<module 'pandas' from 'D:\\anaconda\\Lib\\site-packages\\pandas\\__init__.py'>


In [13]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [17]:
import numpy


In [19]:
import numpy as np

In [23]:
print(np.__version__)

1.26.4


In [45]:
a = np.array([10,27,"play",24,18,1])
print(a)

['10' '27' 'play' '24' '18' '1']


In [31]:
a = np.arange(0,20,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [53]:
a= np.ones((2,6))
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [95]:
arr = [[1,2,3],[4,5,6]]
a=np.ones_like(arr)
print(a)

[[1 1 1]
 [1 1 1]]


In [69]:
a = np.empty((4,2))
print(a)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.02360935e-306]
 [1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306]]


In [81]:
a = np.full((4,2),43)
print(a)

[[43 43]
 [43 43]
 [43 43]
 [43 43]]


In [99]:
a= [1,2,5],[27,82,71]
print(np.repeat(a,5))

[ 1  1  1  1  1  2  2  2  2  2  5  5  5  5  5 27 27 27 27 27 82 82 82 82
 82 71 71 71 71 71]


In [127]:
arr = [[0,2,7],[6,8,9]]
print(np.repeat(arr,4,axis=0)) # according  to graph

[[0 2 7]
 [0 2 7]
 [0 2 7]
 [0 2 7]
 [6 8 9]
 [6 8 9]
 [6 8 9]
 [6 8 9]]


In [131]:
a= np.eye(6,k=1)
print(a)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [155]:
a= np.array(([1,2,3],[4,5,6]))
print(a.ndim)

2


In [161]:
a= np.array([[[1,2,3],[4,5,6],[5,8,9]]])
print (a.ndim)

3


In [163]:
a= np.array([10,20,30,40],ndmin=6)
print(a)

[[[[[[10 20 30 40]]]]]]


In [165]:
print(np.info(a))

class:  ndarray
shape:  (1, 1, 1, 1, 1, 4)
strides:  (16, 16, 16, 16, 16, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x213b3ce5720
byteorder:  little
byteswap:  False
type: int32
None


In [169]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(f"First element from first Dimension {arr[1,4]}")

First element from first Dimension 100


In [202]:
a = np.array([[10,20,30,],[18,19,20],[17,15,18]])
print(a[2,-3])

17


In [210]:
a = np.array([1,2,3,4,5,6,7,])
print(a[1:4:1])

[2 3 4]


In [250]:
a = np.array([1,2,3,4])
print(a[3::1])

[4]
